"""add cfd dashboard tables

Revision ID: 610907c14e50
Revises: b2a4f7e31c01
Create Date: 2026-03-27 14:59:16.666114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610907c14e50'
down_revision: Union[str, None] = 'b2a4f7e31c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfd_runner_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('pending_files', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='singleton_runner_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cfd_simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('meshes', sa.Integer(), nullable=True),
    sa.Column('t_end', sa.Float(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfd_simulations')
    op.drop_table('cfd_runner_state')
    # ### end Alembic commands ###
